# Generated by Django 5.1.4 on 2025-01-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_alter_document_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
